fabric-ca-server:
  image: hyperledger/fabric-ca:amd64-1.5
  environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=fabric-ca-server
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_PORT=7054
  ports:
    - "7054:7054"
  environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  command: sh -c 'fabric-ca-server start -b admin:adminpw --tls.enabled -d'
